#!/usr/bin/env bash
# Self-contained AVX-512 validation for the OpenJPH reversible-wavelet
# dispatch patch.
#   PR branch:  georgehewitt/OpenJPH @ avx512-reversible-wavelet-dispatch
#   Upstream:   aous72/OpenJPH @ master
#
# Target: Arch Linux x86_64 with an AVX-512-capable CPU. Idempotent.
# Run with:
#     curl -sSfL https://raw.githubusercontent.com/georgehewitt/OpenJPH/avx512-validation-helper/test.sh | bash
# Output: a single result file you can send back to George.
set -euo pipefail

WORKDIR="${WORKDIR:-$HOME/openjph-avx512-test}"
UPSTREAM_URL="https://github.com/aous72/OpenJPH.git"
PATCHED_URL="https://github.com/georgehewitt/OpenJPH.git"
PATCHED_BRANCH="avx512-reversible-wavelet-dispatch"

mkdir -p "$WORKDIR"
RESULT="$WORKDIR/result.txt"
: > "$RESULT"

c_red()   { printf '\033[31m%s\033[0m\n' "$*" >&2; }
c_green() { printf '\033[32m%s\033[0m\n' "$*"; }
c_yel()   { printf '\033[33m%s\033[0m\n' "$*"; }
bold()    { printf '\n\033[1m%s\033[0m\n' "$*"; }

# Append a section to the result file.
sec() { printf '\n== %s ==\n' "$*" >> "$RESULT"; }
kv()  { printf '%-18s %s\n' "$1" "$2" >> "$RESULT"; }
say() { printf '%s\n' "$*" >> "$RESULT"; }

trap 'rc=$?; if (( rc != 0 )); then
        printf "\n\033[31mFAILED (exit %d). result.txt at %s — please send it back regardless.\033[0m\n" "$rc" "$RESULT" >&2
        kv "exit_code" "$rc" >> "$RESULT"
      fi' EXIT

# --- header --------------------------------------------------------------
ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
{
  printf '# OpenJPH AVX-512 patch validation\n'
  printf '# Generated by test.sh on %s\n' "$ts"
  printf '# Host: %s\n' "$(hostname)"
} >> "$RESULT"

# --- 1. CPU check --------------------------------------------------------
bold "1. CPU AVX-512 check"
sec "Environment"
kv "kernel" "$(uname -srv)"
kv "distro" "$(. /etc/os-release && echo "$PRETTY_NAME")"
cpu_model=$(grep -m1 'model name' /proc/cpuinfo | sed 's/.*: //')
cores=$(grep -c '^processor' /proc/cpuinfo)
kv "cpu" "$cpu_model"
kv "logical_cpus" "$cores"

if ! grep -q avx512f /proc/cpuinfo; then
    c_red "AVX-512F not present on this CPU — patch path cannot be exercised."
    kv "avx512" "NOT PRESENT — aborting"
    exit 1
fi
all_avx512=$(grep -m1 -oE 'avx512[a-z_0-9]+' /proc/cpuinfo | sort -u | tr '\n' ' ')
kv "avx512" "${all_avx512%% }"
c_green "AVX-512 present: ${all_avx512%% }"

# --- 2. Toolchain --------------------------------------------------------
bold "2. Installing build deps if needed"
need=()
for pkg in base-devel cmake git python coreutils; do
    pacman -Qi "$pkg" >/dev/null 2>&1 || need+=("$pkg")
done
if (( ${#need[@]} > 0 )); then
    c_yel "sudo pacman -S --needed --noconfirm ${need[*]}"
    sudo pacman -S --needed --noconfirm "${need[@]}"
fi

sec "Toolchain"
kv "gcc"    "$(gcc --version | head -1)"
kv "cmake"  "$(cmake --version | head -1)"
kv "python" "$(python --version)"
kv "git"    "$(git --version)"

# --- 3. Sources ----------------------------------------------------------
bold "3. Fetching unpatched + patched"
cd "$WORKDIR"
clone_or_fetch() {
    local url="$1" dir="$2" branch="$3"
    if [[ -d "$dir/.git" ]]; then
        (cd "$dir" && git fetch -q origin "$branch" \
                       && git checkout -q "$branch" \
                       && git reset -q --hard "origin/$branch")
    else
        git clone -q "$url" "$dir"
        (cd "$dir" && git checkout -q "$branch")
    fi
}
clone_or_fetch "$UPSTREAM_URL" unpatched master
clone_or_fetch "$PATCHED_URL"  patched   "$PATCHED_BRANCH"
unpatched_sha=$(cd unpatched && git rev-parse --short HEAD)
patched_sha=$(cd patched   && git rev-parse --short HEAD)

sec "Sources"
kv "unpatched" "aous72/OpenJPH master @ $unpatched_sha"
kv "patched"   "georgehewitt/OpenJPH $PATCHED_BRANCH @ $patched_sha"

# --- 4. Build ------------------------------------------------------------
bold "4. Building both (Release)"
for d in unpatched patched; do
    rm -rf "$d/build"
    mkdir "$d/build"
    (cd "$d/build" \
         && cmake -DCMAKE_BUILD_TYPE=Release .. >/dev/null 2>&1 \
         && make -j"$(nproc)" >/dev/null 2>&1) \
        || { c_red "build failed for $d"; kv "build_$d" "FAILED"; exit 2; }
    echo "  $d built"
done

# --- 5. ctest ------------------------------------------------------------
bold "5. ctest on patched build"
ctest_log="$WORKDIR/ctest.log"
(cd patched/build && ctest --output-on-failure 2>&1) > "$ctest_log"

sec "ctest (patched)"
tail -5 "$ctest_log" >> "$RESULT"
if grep -q '100% tests passed, 0 tests failed' "$ctest_log"; then
    c_green "  $(grep -oE '[0-9]+% tests passed.*' "$ctest_log" | head -1)"
    kv "verdict" "all pass"
else
    c_red "  ctest FAILED"
    kv "verdict" "FAIL — see ctest.log"
    cp "$ctest_log" "$WORKDIR/ctest_FAILED.log"
    exit 3
fi

# --- 6. Bit-exact reversible roundtrip -----------------------------------
bold "6. Bit-exact reversible roundtrip (2048x2048x16-bit)"
python - <<'PY'
import random
random.seed(0xC1A1)
W = H = 2048
with open("input.pgm", "wb") as f:
    f.write(f"P5\n{W} {H}\n65535\n".encode())
    f.write(random.randbytes(W * H * 2))
PY
./unpatched/build/bin/ojph_compress -i input.pgm -o unpatched.j2c \
    -num_decomps 5 -reversible true >/dev/null
./patched/build/bin/ojph_compress -i input.pgm -o patched.j2c \
    -num_decomps 5 -reversible true >/dev/null

u_sz=$(stat -c '%s' unpatched.j2c)
p_sz=$(stat -c '%s' patched.j2c)
u_md=$(md5sum unpatched.j2c | cut -d' ' -f1)
p_md=$(md5sum patched.j2c   | cut -d' ' -f1)

sec "Bit-exactness (reversible, 2048x2048x16-bit, num_decomps=5)"
kv "unpatched_size" "$u_sz B"
kv "patched_size"   "$p_sz B"
kv "unpatched_md5"  "$u_md"
kv "patched_md5"    "$p_md"

if cmp -s unpatched.j2c patched.j2c; then
    c_green "  Codestreams byte-identical ($p_sz bytes, md5 $p_md)"
    kv "verdict" "BIT-EXACT"
else
    c_red "  Codestreams DIFFER — saving samples for forensic inspection"
    kv "verdict" "DIVERGED"
    cmp -l unpatched.j2c patched.j2c 2>/dev/null | head -20 \
        > "$WORKDIR/codestream_diff_head.txt" || true
    # Bundle both codestreams for the report.
    tar -cJf "$WORKDIR/codestreams.tar.xz" unpatched.j2c patched.j2c \
        2>/dev/null || tar -czf "$WORKDIR/codestreams.tar.gz" \
                              unpatched.j2c patched.j2c
    exit 4
fi

# --- 7. Encode speed -----------------------------------------------------
bold "7. Encode speed (5 runs each, median + range)"
time_exe() {
    python - "$1" <<'PY'
import subprocess, sys, time
exe = sys.argv[1]
ts = []
for _ in range(5):
    t0 = time.perf_counter()
    subprocess.run([exe, "-i", "input.pgm", "-o", "/tmp/oj_bench.j2c",
                    "-num_decomps", "5", "-reversible", "true"],
                   check=True, stdout=subprocess.DEVNULL)
    ts.append(time.perf_counter() - t0)
ts.sort()
print(f"{ts[2]*1000:.1f} {ts[0]*1000:.1f} {ts[4]*1000:.1f}")
PY
}
u_t=$(time_exe ./unpatched/build/bin/ojph_compress)
p_t=$(time_exe ./patched/build/bin/ojph_compress)
read u_med u_min u_max <<<"$u_t"
read p_med p_min p_max <<<"$p_t"
ratio=$(python -c "print(f'{$u_med / $p_med:.3f}')")
delta=$(python -c "print(f'{($u_med - $p_med):+.1f}')")

sec "Encode timings (ms, 5 runs each)"
kv "unpatched_median" "$u_med  (min $u_min max $u_max)"
kv "patched_median"   "$p_med  (min $p_min max $p_max)"
kv "delta_ms"         "$delta"
kv "speedup"          "${ratio}x"

# --- 8. Verdict ----------------------------------------------------------
sec "Verdict"
if python -c "import sys; sys.exit(0 if $ratio >= 1.005 else 1)"; then
    say "PASS — bit-exact and measurable speedup."
    c_green "PASS: bit-exact + ${ratio}x speedup on AVX-512."
else
    say "BIT-EXACT but speedup ratio $ratio is within noise. Wavelet may"
    say "be a small fraction of total encode time at this image size."
    c_yel "PASS (bit-exact) but speedup ${ratio}x is small."
fi

# --- 9. Closing ----------------------------------------------------------
printf "\n"
bold "Done."
echo
echo "Send this single file back:"
echo
echo "  $RESULT"
echo
echo "  cat $RESULT      # to view"
echo "  xclip -sel c < $RESULT   # to copy to clipboard"
echo
